//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace projectONE
{
    using System;
    using System.Collections.Generic;
    
    public partial class ArchiveStock
    {
        public int NumArch { get; set; }
        public System.DateTime DateArch { get; set; }
        public string NumArt { get; set; }
        public Nullable<decimal> Stock { get; set; }
        public Nullable<decimal> QteS { get; set; }
        public Nullable<decimal> MontantS { get; set; }
        public Nullable<decimal> QteE { get; set; }
        public Nullable<decimal> MontantE { get; set; }
    }
}
