//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace projectONE
{
    using System;
    using System.Collections.Generic;
    
    public partial class Article
    {
        public string Num_At { get; set; }
        public string Designation { get; set; }
        public double PU { get; set; }
        public double QteS { get; set; }
        public int TVA { get; set; }
        public string num_fardeau { get; set; }
        public Nullable<int> Num_Fa { get; set; }
        public string unite { get; set; }
    }
}
