//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace projectONE
{
    using System;
    using System.Collections.Generic;
    
    public partial class Collection
    {
        public string NumCollection { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> Nombre { get; set; }
        public Nullable<int> Nbcement { get; set; }
        public Nullable<int> NumWeek { get; set; }
        public string typeTobiya { get; set; }
        public Nullable<int> Nb_Collection { get; set; }
        public Nullable<double> Prix { get; set; }
    }
}
