//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace projectONE
{
    using System;
    using System.Collections.Generic;
    
    public partial class CommandeVente
    {
        public int Num_CmdV { get; set; }
        public System.DateTime DateCmd { get; set; }
        public bool IsFacture { get; set; }
        public Nullable<int> Num_Clt { get; set; }
    }
}
