//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace projectONE
{
    using System;
    using System.Collections.Generic;
    
    public partial class CommandeAch
    {
        public int Num_Cmd { get; set; }
        public System.DateTime DateAch { get; set; }
        public string IDFActureA { get; set; }
        public Nullable<int> Num_Fr { get; set; }
    }
}
