//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace projectONE
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetailAchat
    {
        public string Num_At { get; set; }
        public int Num_Cmd { get; set; }
        public double Qte { get; set; }
        public double PrixA { get; set; }
    }
}
