//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace projectONE
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetailFac
    {
        public Nullable<int> Num_Fac { get; set; }
        public Nullable<int> Num_CmdV { get; set; }
        public int IDCmdFact { get; set; }
    }
}
