//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace projectONE
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fournisseur
    {
        public int Num_Fr { get; set; }
        public string NomF { get; set; }
        public string Ville { get; set; }
        public string Adresse { get; set; }
        public string Tele { get; set; }
        public string Email { get; set; }
    }
}
