//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace projectONE
{
    using System;
    using System.Collections.Generic;
    
    public partial class Location
    {
        public int NumLoc { get; set; }
        public Nullable<System.DateTime> DateDebut { get; set; }
        public Nullable<System.DateTime> DateFin { get; set; }
        public string Matricule { get; set; }
        public Nullable<int> Num_Clt { get; set; }
        public string Unite { get; set; }
        public Nullable<double> Montant { get; set; }
        public Nullable<double> Montant_paye { get; set; }
        public Nullable<double> reste { get; set; }
    }
}
