//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace projectONE
{
    using System;
    using System.Collections.Generic;
    
    public partial class poitage
    {
        public int Nump { get; set; }
        public string Cin { get; set; }
        public Nullable<double> Avence { get; set; }
        public string NumCollection { get; set; }
    }
}
