//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace projectONE
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reglement
    {
        public int Num_Reg { get; set; }
        public double Montant { get; set; }
        public string NumChe { get; set; }
        public Nullable<int> Num_ModeReg { get; set; }
        public Nullable<int> Num_Bq { get; set; }
        public Nullable<double> montantDepose { get; set; }
        public Nullable<double> reste { get; set; }
    }
}
