//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace projectONE
{
    using System;
    using System.Collections.Generic;
    
    public partial class Utilisateur
    {
        public int Id_user { get; set; }
        public string User { get; set; }
        public string MP { get; set; }
    }
}
